ENABLE_LINTERS:
  - PYTHON_RUFF
  - PYTHON_RUFF_FORMAT
  - PYTHON_MYPY
  - PYTHON_BANDIT
  - REPOSITORY_TRIVY
  - YAML_YAMLLINT
  - MARKDOWN_MARKDOWNLINT

FLAVOR_SUGGESTIONS: false

PYTHON_BANDIT_ARGUMENTS: "-c linters/.bandit.yml"
PYTHON_MYPY_CONFIG_FILE: linters/.mypy.ini
